- hosts: localhost
  roles:
    - get_post_vault_keys

  # 
  # ------------- REMOVE EMPTY VALUES AND PRINT TO CONSOLE -------------
  # - name: Remove empty values from host_data
    # ansible.builtin.set_fact:
      # host_data_filtered: "{{ host_data | dict2items | selectattr('value', 'ne', '') | items2dict }}"
  # 
  # - name: Print Out Data to Observe (Pre Modification)
    # tags: never, clean
    # debug:
      # var: host_data_filtered